# Generated by Django 3.2.20 on 2023-08-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=100)),
                ('userphone', models.ImageField(max_length=10, upload_to='')),
                ('useraddress', models.TextField(max_length=200)),
            ],
        ),
    ]
