# Generated by Django 3.2.20 on 2023-08-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userphone',
            field=models.IntegerField(max_length=10),
        ),
    ]
